### ISSUE TITLE
Latest version detection broken

### ISSUE THREAD

**Issue by emlynmac** [coppit/docker-xeoma#16]
Just tried to update / build fresh image. On startup, it fails:

```
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
Mar  3 03:50:23 a0741c0d373e syslog-ng[12]: syslog-ng starting up; version='3.13.2'
*** Running /etc/my_init.d/30_parse_config_file.sh...
Configuration:
  PASSWORD=<hidden>
  VERSION=latest
*** Running /etc/my_init.d/40_install_xeoma.py...
2020-03-03 03:50:24 Determining version of Xeoma to use
2020-03-03 03:50:24 Config version is "latest"
2020-03-03 03:50:24 Fetching version information from Felenasoft at http://felenasoft.com/xeoma/downloads/version3.xml
Traceback (most recent call last):
  File "/etc/my_init.d/40_install_xeoma.py", line 182, in <module>
    version_number, download_url, alternate_download_url = resolve_download_info()
  File "/etc/my_init.d/40_install_xeoma.py", line 70, in resolve_download_info
    version_number, download_url, alternate_download_url = latest_version()
  File "/etc/my_init.d/40_install_xeoma.py", line 38, in latest_version
    e = xml.etree.ElementTree.ElementTree(file=urllib.request.urlopen(VERSION_URL)).getroot()
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 557, in __init__
    self.parse(file)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: no element found: line 38, column 1
*** /etc/my_init.d/40_install_xeoma.py failed with status 1

*** Killing all processes...
Mar  3 03:50:25 a0741c0d373e syslog-ng[12]: syslog-ng shutting down; version='3.13.2'
```

Is this because the XML is malformed from the underlying site?
`http://felenasoft.com/xeoma/downloads/version3.xml`

Hardcoding the release to 20.2.13 in the config file seems to make this work again

**Comment by abeksis** [comment]
The same for me too:

```

*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
Apr 22 08:47:50 0434f1975779 syslog-ng[13]: syslog-ng starting up; version='3.13.2'

*** Running /etc/my_init.d/30_parse_config_file.sh...
Creating config file. Please do not forget to edit it to specify your settings!
*** /etc/my_init.d/30_parse_config_file.sh failed with status 1


*** Killing all processes...
Apr 22 08:47:51 0434f1975779 syslog-ng[13]: syslog-ng shutting down; version='3.13.2'

```

**Comment by andrew-from-toronto** [comment]
http://felenasoft.com/xeoma/downloads/version3.xml is 404ing now - http://felenasoft.com/xeoma/downloads/version.xml does resolve. Does this just need a patch to the correct URL?

**Comment by neurocis** [comment]
3rd:

```
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
Dec 15 02:43:40 fd649a6d6aed syslog-ng[13]: syslog-ng starting up; version='3.13.2'

*** Running /etc/my_init.d/30_parse_config_file.sh...
Configuration:
PASSWORD=<hidden>
VERSION=latest

*** Running /etc/my_init.d/40_install_xeoma.py...
2020-12-15 02:43:40 Determining version of Xeoma to use

2020-12-15 02:43:40 Config version is "latest"

2020-12-15 02:43:40 Fetching version information from Felenasoft at http://felenasoft.com/xeoma/downloads/version3.xml

Traceback (most recent call last):
File "/etc/my_init.d/40_install_xeoma.py", line 182, in <module>
version_number, download_url, alternate_download_url = resolve_download_info()
File "/etc/my_init.d/40_install_xeoma.py", line 70, in resolve_download_info
version_number, download_url, alternate_download_url = latest_version()
File "/etc/my_init.d/40_install_xeoma.py", line 38, in latest_version
e = xml.etree.ElementTree.ElementTree(file=urllib.request.urlopen(VERSION_URL)).getroot()
File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
return opener.open(url, data, timeout)
File "/usr/lib/python3.6/urllib/request.py", line 532, in open
response = meth(req, response)
File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
'http', request, response, code, msg, hdrs)
File "/usr/lib/python3.6/urllib/request.py", line 570, in error

return self._call_chain(*args)
File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
result = func(*args)
File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

Dec 15 02:43:40 fd649a6d6aed syslog-ng[13]: syslog-ng shutting down; version='3.13.2'

*** /etc/my_init.d/40_install_xeoma.py failed with status 1


*** Killing all processes...
```

I think I will fork, fix and PR, will post back if I do fix.

**Comment by neurocis** [comment]
This looks to be the file version3.xml is no longer on the felenasoft website, I actually opted to just specify VERSION=20.11.30 which resolved my issue.

**Comment by neurocis** [comment]
Update:
```
 ---- On Tue, 15 Dec 2020 00:34:18 -0700 Felenasoft Support <support@felenasoft.com> wrote ----
 >         Hi,
 > The file version3.xml has been temporarily removed due to an issue with the current version (20.11.30). We intend to fix the issue and update the version ASAP.
 > Apologies for the inconvenience.
 > If you have any questions, suggestions, etc, please let us know. We will be glad to help you.
 > Paul,
 > FelenaSoft Company
 > support@felenasoft.com - free support
 > +44(20)3807-04-87 (08:00-15:00 UTC)
 > Skype: felenasoft_2
```

**Comment by abeksis** [comment]
me to

**Comment by andrew-from-toronto** [comment]
Pinning version as a temporary workaround like @neurocis mentioned solved this for me as well

**Comment by abeksis** [comment]
What did you write under the version? Can you show?

**Comment by hflatoey** [comment]
> What did you write under the version? Can you show?

In xeoma.conf
Change VERSION=latest to VERSION=20.11.30
