### ISSUE TITLE
Xeoma won't launch.  Xeoma website changed.

### ISSUE THREAD

**Issue by rsteckler** [coppit/docker-xeoma#9]
When it starts, this container downloads a versions file from the xeoma website.  That file no longer contains the linux key that the container is looking for:
```

*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
Apr 25 04:16:57 camera-deployment-66cdc6b7bd-mdxth syslog-ng[13]: syslog-ng starting up; version='3.13.2'
*** Running /etc/my_init.d/30_parse_config_file.sh...
Configuration:
  PASSWORD=<hidden>
  VERSION=latest
*** Running /etc/my_init.d/40_install_xeoma.py...
2019-04-25 04:16:59 Determining version of Xeoma to use
2019-04-25 04:16:59 Config version is "latest"
2019-04-25 04:16:59 Fetching version information from Felenasoft at http://felenasoft.com/xeoma/downloads/version2.xml
Traceback (most recent call last):
  File "/etc/my_init.d/40_install_xeoma.py", line 176, in <module>
    version_number, download_url, alternate_download_url = resolve_download_info()
  File "/etc/my_init.d/40_install_xeoma.py", line 64, in resolve_download_info
    version_number, download_url, alternate_download_url = latest_version()
  File "/etc/my_init.d/40_install_xeoma.py", line 44, in latest_version
    download_url = e.find('{}platform[@name="linux64"]'.format(beta_string)).find('url').text
AttributeError: 'NoneType' object has no attribute 'find'
*** /etc/my_init.d/40_install_xeoma.py failed with status 1
 *** Killing all processes...
Apr 25 04:16:59 camera-deployment-66cdc6b7bd-mdxth syslog-ng[13]: syslog-ng shutting down; version='3.13.2'
```

**Comment by CRACKISH** [comment]
Same here ((

**Comment by coppit** [comment]
Fixed in the latest version.
